name: Build packages and push to binary cache
on:
  pull_request:
  push:
  repository_dispatch:
    types: [rebuild]
  schedule:
    - cron: 0 */6 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nix-channel:
          - nixpkgs-unstable
          - nixos-unstable
          - nixos-20.09-small
          - nixos-20.09
          - nixos-21.05-small
          - nixos-21.05

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:${{ matrix.nix-channel }}

      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: gerschtli
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Build packages and push to cachix
        run: nix-build ci.nix -A buildOutputs --keep-going --show-trace
