name: Build packages and push to binary cache
on:
  pull_request:
  push:
  repository_dispatch:
    types: [rebuild]
  schedule:
    - cron: 0 */6 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nix-channel:
          - nixpkgs-unstable
          - nixos-unstable
          - nixos-20.03-small
          - nixos-20.03

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: Gerschtli/install-nix-action@nix-path
        with:
          NIX_PATH: nixpkgs=channel:${{ matrix.nix-channel }}

      - name: Build packages and push to cachix
        uses: cachix/cachix-action@v3
        with:
          name: gerschtli
          file: ci.nix
          attributes: buildOutputs
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          nixBuildArgs: --keep-going --show-trace
