name: Update dwm-status revision
on:
  repository_dispatch:
    types: [update-dwm-status]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v14

      - name: Update revision and sha256
        uses: Gerschtli/generate-nix-hash@v1
        with:
          rev: ${{ github.event.client_payload.commit_id }}
          owner: Gerschtli
          repo: dwm-status
          file: pkgs/dwm-status/config.json

      - name: Commit and push changes
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          commit-message: Update dwm-status
          name: Update Bot
          email: update@bot
          rebase: true

      - name: Trigger build workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: rebuild
