name: Update dwm-status revision
on:
  repository_dispatch:
    types: [update-dwm-status]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: Gerschtli/install-nix-action@nix-path
        with:
          NIX_PATH: nixpkgs=channel:nixpkgs-unstable

      - name: Update revision and sha256
        run: |
          rev=${{ github.event.client_payload.commit_id }}
          echo "rev: ${rev}"

          sha256=$(nix-prefetch-url --unpack "https://github.com/Gerschtli/dwm-status/archive/${rev}.tar.gz" 2> /dev/null)
          echo "sha256: ${sha256}"

          cat > ./pkgs/dwm-status/config.json <<EOF
          {
            "rev": "${rev}",
            "sha256": "${sha256}"
          }
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.name "Update Bot"
          git config --local user.email "update@bot"
          git commit --all --message "Update dwm-status"
          git push origin master

      - name: Trigger build workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: rebuild
